version: '3.4'

services:
  createreactapp:
    image: createreactapp
    build:
      context: create-react-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
